### ISSUE TITLE
Should you set pc+4 to rd when exec JALR?

### ISSUE THREAD

**Issue by qiluge** [racerxdl/riscv-emulator#1]
In the file `core/instructionDecoder`, line 203: ```rv32.Registers.SetInteger(rd, t)```, may be it should be ```rv32.Registers.SetInteger(rd, t+4)```.

At riscv-spec, the JALR should be:
![image](https://user-images.githubusercontent.com/19525062/186844089-6b4f0116-4af8-479d-b2ce-9386f739c479.png)

**Comment by racerxdl** [comment]
Yes, but the runInstruction assumes the PC has been already incremented. 
I forgot to put a comment about it, but you can see the first line here: https://github.com/racerxdl/riscv-emulator/blob/main/core/instructionDecoder.go#L32 that it prints out pc-4 as the current executing offset.

If you see here ( https://github.com/racerxdl/riscv-emulator/blob/main/core/cpu.go#L79-L80 ) the CPU itself increments the PC before the instruction runs, so the JALR sets `rd` to the next instruction correctly (which would be the `jalr` position + 4 bytes)

**Comment by qiluge** [comment]
Yes, I see. Sorry.
